import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

import { auth, db } from "../../firebase/firebase";

import { doc, getDoc } from "firebase/firestore";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Restaurant() {
  const router = useRouter();
  const { name } = router.query;

  const [reviewList, setReviewList] = useState();

  const getData = async () => {
    const docRef = doc(db, "building", "ZlRdaGwaJHMHGrUU9dJg");
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      console.log("Building data:", docSnap.data());
      const list = docSnap.data().reviews;
      setReviewList(list);
    } else {
      // doc.data() will be undefined in this case
      console.log("No such document!");
    }
  };

  const getReviews = async (reviewId) => {
    const docRef = doc(db, "buildingReviews", reviewId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      console.log("Review data:", docSnap.data());
    } else {
      // doc.data() will be undefined in this case
      console.log("No such document!");
    }
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Building Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Building: {name}</div>
        {console.log(reviewList)}
        {reviewList?.map((review, id) => (
            <div>
                {review}
            </div>
        ))}
      </main>
    </>
  );
}
