import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Study.module.css";
import { useRouter } from "next/router";

import { auth, db } from "../../firebase/firebase";

import { doc, getDoc } from "firebase/firestore";
import { useEffect, useState } from "react";
import StudyReviews from "@/components/studyReviews";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function StudyreviewsPage() {
  const router = useRouter();
  const { name } = router.query;

  const [sectionData, setSectionData] = useState();
  const [selectSection, setSelectSection] = useState(0);

  const getData = async () => {
    const docRef = doc(db, "building", "ZlRdaGwaJHMHGrUU9dJg");
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      console.log("Building data:", docSnap.data());
      const sectionSnapData = docSnap.data().sections;
      setSectionData(sectionSnapData);
    } else {
      // doc.data() will be undefined in this case
      console.log("No such document!");
    }
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Building Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div>Building: {name}</div>
        <button onClick={() => setSelectSection(1)}>First Floor</button>
        <button onClick={() => setSelectSection(2)}>Second Floor</button>
        {selectSection != 0
          ? sectionData[selectSection - 1].reviews.map((review, id) => (
              <StudyReviews review={review} key={id} />
            ))
          : null}
      </main>
    </>
  );
}
